# Generated by Django 4.2.17 on 2025-04-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatbot",
            name="instructions",
            field=models.TextField(
                default="Sen destek asistanısın. Kullanıcıların sorularını enfazla 4 cümlede yanıtlayacaksın. Soru dili ne ise o dilde cevap ver. Eğer sorunun cevabını bilmiyorsan, kullanıcıyı bir telefona veya mail adresine yönlendir.",
                help_text="Destek konusunu belirtin. cevaplama şeklini veya kısıtları söyleyebilirsiniz. bilmediği konularda bir telefona veya mail adresine yönlendirme yapılabilir.",
            ),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="temperature",
            field=models.FloatField(
                default=0.7,
                help_text="Sıcaklık değeri. 0.0 ile 1.0 arasında olmalıdır. 0.0  daha net cevaplar fakat az yaratıcılık, 1.0 en fazla üretken konunun özeünnden uzaklaşmasına sebep olabilir",
            ),
        ),
        migrations.AlterField(
            model_name="chatbot",
            name="widget_color",
            field=models.CharField(
                default="#3B82F6",
                help_text="Chatbot widget rengi. Hex kodu olarak girin.",
                max_length=7,
            ),
        ),
    ]
