# Generated by Django 4.2.17 on 2025-03-31 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DokumanTipi",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tip", models.CharField(max_length=20, verbose_name="Dokuman Tipi")),
            ],
        ),
        migrations.CreateModel(
            name="Dosyalar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to="", verbose_name="Dosya")),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "created_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Eklenme Tarihi"
                    ),
                ),
                (
                    "secret",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Job secret"
                    ),
                ),
                (
                    "secret_valid",
                    models.DateField(
                        blank=True, null=True, verbose_name="Secret Geçerlilik Tarihi"
                    ),
                ),
            ],
        ),
    ]
