# Generated by Django 4.2.17 on 2025-03-31 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saas", "0001_initial"),
        ("dokumanlar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dosyalar",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="dosyalar",
            name="created_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ekleyen kullanıcı",
            ),
        ),
        migrations.AddField(
            model_name="dosyalar",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="dokumanlar.dokumantipi",
                verbose_name="Dokuman Tipi",
            ),
        ),
        migrations.AddField(
            model_name="dokumantipi",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
    ]
