# Generated by Django 4.2.17 on 2025-03-31 16:55

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DuzenliGorevTanim",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Düzenli Görev Başlığı"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Görev Detayları"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Başlangıç Tarihi",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "repeat_type",
                    models.CharField(
                        choices=[
                            ("1", "Günlük"),
                            ("2", "Haftalık"),
                            ("3", "Aylık"),
                            ("4", "Yıllık"),
                            ("5", "Saatlik"),
                        ],
                        default="1",
                        max_length=1,
                        verbose_name="Tekrar Tipi",
                    ),
                ),
                (
                    "frequency",
                    models.IntegerField(default=1, verbose_name="Tekrar Sıklığı"),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Haftanın Günleri"
                    ),
                ),
                (
                    "days_of_month",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Ayın Günleri"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Döküman (Varsa)",
                    ),
                ),
                (
                    "numberOfDayOpen",
                    models.IntegerField(
                        default=3, verbose_name="Açık Kalma Gün Sayısı"
                    ),
                ),
                (
                    "numberOfDayCreate",
                    models.IntegerField(
                        default=3, verbose_name="Kaç gün önce oluşturulacak"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
        ),
        migrations.CreateModel(
            name="Gorevler",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Görev Başlığı"),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Görev Detayları"
                    ),
                ),
                (
                    "solution",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Tamamlama Özeti"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planlanan Başlangıç Tarihi"
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Planlanan Bitiş Tarihi"
                    ),
                ),
                ("closed_date", models.DateTimeField(blank=True, null=True)),
                (
                    "dokuman",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Döküman"
                    ),
                ),
                ("secret", models.CharField(max_length=50, verbose_name="Job secret")),
                (
                    "secret_expiredate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Secret Geçerlilik Tarihi"
                    ),
                ),
                (
                    "complete_level",
                    models.IntegerField(default=0, verbose_name="Tamamlanma Oranı"),
                ),
                ("harcama", models.FloatField(default=0, verbose_name="Harcama")),
                ("revision", models.IntegerField(default=1, verbose_name="Revizyon")),
                (
                    "res_user_name",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Sorumlu Ad/Soyad",
                    ),
                ),
                (
                    "res_user_telephone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Sorumlu kullanıcı telefonu",
                    ),
                ),
                (
                    "res_user_email",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Sorumlu kullanıcı email",
                    ),
                ),
                ("planed_startdate", models.DateField(blank=True, null=True)),
                ("planed_date", models.DateField(blank=True, null=True)),
                ("revision_date", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("priority", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="GorevlerStatu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("statu", models.CharField(max_length=30, verbose_name="Gorev Statu")),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "is_end",
                    models.BooleanField(
                        default=False, verbose_name="Görev Sonlandırma"
                    ),
                ),
                (
                    "is_start",
                    models.BooleanField(default=False, verbose_name="Görev Başlatma"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GorevNotu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField()),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "dokuman",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Döküman"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GorevType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(max_length=30, verbose_name="Hatırlatma Tipi"),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField()),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Hatırlatma Açıklaması",
                    ),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Hatırlatma Tarihi"
                    ),
                ),
                (
                    "time",
                    models.IntegerField(
                        default=1, verbose_name="Ne kadar önceden hatırlatılsın"
                    ),
                ),
                (
                    "time_type",
                    models.CharField(
                        choices=[
                            ("1", "Dakika"),
                            ("2", "Saat"),
                            ("3", "Gün"),
                            ("4", "Hafta"),
                            ("5", "Ay"),
                        ],
                        default="3",
                        max_length=1,
                        verbose_name="Saat / Gün / Hafta ...",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReminderType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(max_length=30, verbose_name="Hatırlatma Tipi"),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
            ],
        ),
    ]
