# Generated by Django 4.2.17 on 2025-03-31 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
        ("gorevler", "0001_initial"),
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="remindertype",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="gorev",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gorevler.gorevler",
                verbose_name="gorev",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="open_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kayıdı açan",
            ),
        ),
        migrations.AddField(
            model_name="reminder",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gorevler.remindertype",
                verbose_name="Hatırlatma Tipi",
            ),
        ),
        migrations.AddField(
            model_name="gorevtype",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="gorevnotu",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="gorevnotu",
            name="gorev",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gorevler.gorevler",
                verbose_name="gorev",
            ),
        ),
        migrations.AddField(
            model_name="gorevnotu",
            name="open_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kayıdı açan",
            ),
        ),
        migrations.AddField(
            model_name="gorevlerstatu",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.color",
                verbose_name="Renk",
            ),
        ),
        migrations.AddField(
            model_name="gorevlerstatu",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.departments",
                verbose_name="Departman",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="open_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="openUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kaydı Açan",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Görev Sorumlusu",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="scheduledTask",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gorevler.duzenligorevtanim",
                verbose_name="Düzenli Görev",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="statu",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gorevler.gorevlerstatu",
            ),
        ),
        migrations.AddField(
            model_name="gorevler",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gorevler.gorevtype",
                verbose_name="Görev Tipi",
            ),
        ),
        migrations.AddField(
            model_name="duzenligorevtanim",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.color",
                verbose_name="Renk",
            ),
        ),
        migrations.AddField(
            model_name="duzenligorevtanim",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AddField(
            model_name="duzenligorevtanim",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duzenliGorevCreatedUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kaydı Açan",
            ),
        ),
        migrations.AddField(
            model_name="duzenligorevtanim",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.departments",
                verbose_name="Departman",
            ),
        ),
        migrations.AddField(
            model_name="duzenligorevtanim",
            name="responsible_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="duzenliGorevresUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Görev Sorumlusu",
            ),
        ),
    ]
