# Generated by Django 4.2.17 on 2025-03-31 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="Firma Adı")),
                (
                    "adres",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Adres"
                    ),
                ),
                (
                    "telefon",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "web",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Web Sayfası",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logo/", verbose_name="Logo"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Aktif/Pasif"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma tarihi",
                    ),
                ),
                (
                    "faturaDetay",
                    models.TextField(
                        blank=True, null=True, verbose_name="Fatura DetayBilgileri"
                    ),
                ),
                (
                    "vergi_dairesi",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vergi Dairesi",
                    ),
                ),
                (
                    "vergi_no",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Vergi Numarası",
                    ),
                ),
                (
                    "orderFormTemplate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Sipariş Formu Şablonu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Durum Adı")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Aktif/Pasif"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma tarihi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Sektor Adı")),
            ],
        ),
        migrations.CreateModel(
            name="Modules",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, verbose_name="Modül Adı")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Açıklama"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Aktif/Pasif"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma tarihi",
                    ),
                ),
                (
                    "userGroup",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Kullanıcı Grubu",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyModules",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Aktif/Pasif"),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Oluşturulma tarihi",
                    ),
                ),
                (
                    "expire_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Bitiş Tarihi"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saas.company",
                        verbose_name="Firma",
                    ),
                ),
                (
                    "modules",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saas.modules",
                        verbose_name="Modül",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Company_Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ulke",
                    models.CharField(
                        default="Türkiye", max_length=30, verbose_name="ULKE"
                    ),
                ),
                (
                    "il",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="IL"
                    ),
                ),
                (
                    "ilce",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="İLÇE"
                    ),
                ),
                (
                    "mahalle",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="MAHALLE"
                    ),
                ),
                (
                    "adres",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="ADRES"
                    ),
                ),
                (
                    "map_link",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="GOOGLE MAP"
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Açıklama(kısa/kod)",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="saas.company",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.sector",
                verbose_name="Sektor",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="saas.companystatus",
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sorumlu",
            ),
        ),
    ]
