# Generated by Django 4.2.17 on 2025-04-02 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0002_remove_company_orderformtemplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.sector",
                verbose_name="Sektor",
            ),
        ),
    ]
