# Generated by Django 4.2.17 on 2025-04-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0003_alter_company_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "ozellik",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Özellik"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("String", "String"),
                            ("Int", "Int"),
                            ("Float", "Float"),
                            ("Bool", "Bool"),
                        ],
                        default="Bool",
                        max_length=10,
                        verbose_name="Tip",
                    ),
                ),
                (
                    "aciklama",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Açıklama"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanySettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("deger", models.CharField(max_length=20, verbose_name="Değer ")),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="saas.company",
                    ),
                ),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="saas.settings",
                        verbose_name="Özellik",
                    ),
                ),
            ],
        ),
    ]
