# Generated by Django 4.2.17 on 2025-03-31 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("saas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150, unique=True)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Renk Kodu(bootstrap)",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Renk Kodu(rgb)",
                    ),
                ),
                (
                    "satir_color_code",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Satır Renk Kodu(rgb)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("department_number", models.CharField(max_length=150, unique=True)),
                ("title", models.CharField(max_length=150, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="saas.company",
                    ),
                ),
                (
                    "main_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.departments",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmsProblem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now=True)),
                ("telephone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("message", models.TextField(max_length=500, verbose_name="Mesaj")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="10",
                        max_length=3,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_date", models.DateTimeField(auto_now=True, null=True)),
                ("send_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(
                        blank=True,
                        default="10",
                        max_length=15,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "try_count",
                    models.IntegerField(default=0, verbose_name="Deneme sayısı"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sube",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Yetenek",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Yetki",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Yetkilendirme",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("siparis_yonetimi", "Satış girişi için gerekli yetki"),
                    ("siparis_listele", "Satışları listeleme"),
                    ("urun_listele", "Ürün Listeleme"),
                    ("urun_yonetim", "Ürün ekleme,güncelleme,deaktif etme"),
                    ("musteri_listele", "Müşteri listeleme"),
                    ("musteri_yonetim", "Müşteri ekleme,güncelleme,silme"),
                    ("kullanici_listeleme", "Kullanıcı listeleme"),
                    ("kullanici_yonetim", "Kullanıcı yönetimi"),
                    ("rezervasyon_listele", "Rezervasyonları listeleme görüntüleme"),
                    ("rezervasyon_yonetim", "Rezervasyon yönetim işlemleri"),
                    ("rapor_listele", "Rapor listeleme"),
                    ("log_listeleme", "Logları görme"),
                    ("musterisikayet_listeleme", "Müşteri şikayetleri listele gör"),
                    ("musterisikayet_yonetim", "Müşteri şikayetleri yönetimi"),
                    ("workflow_operasyon", "Workflow Operasyon "),
                    ("workflow_planlama", "Workflow Planlama  "),
                    ("workflow_depo", "Workflow Depo "),
                    ("workflow_uretim", "Workflow Uretim "),
                    ("workflow_islem", "Workflow üzerinde işlem yapabilme yetkisi "),
                    ("test", "test yetkisi"),
                ),
            },
        ),
        migrations.CreateModel(
            name="ShortCut",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="Başlık")),
                ("url", models.CharField(max_length=200, verbose_name="Url")),
                (
                    "icon",
                    models.CharField(
                        default="fas fa-home", max_length=50, verbose_name="Icon"
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="Sıra")),
                (
                    "color",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.color",
                        verbose_name="Renk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logging",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "log_type",
                    models.CharField(
                        default="genel", max_length=20, verbose_name="Açıklama"
                    ),
                ),
                ("type_id", models.IntegerField(default=1, verbose_name="Order ID")),
                ("aciklama", models.CharField(max_length=100, verbose_name="Açıklama")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="10",
                        max_length=3,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profilePhoto",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=user.models.profile_upload_to,
                        verbose_name="Problem dosya/resim",
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, default="Kullanıcı", max_length=20),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="Telefon(iş)"
                    ),
                ),
                (
                    "telephone2",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Telefon(şahsi)",
                    ),
                ),
                (
                    "yetenek",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Yetenek"
                    ),
                ),
                ("otp", models.CharField(blank=True, max_length=4, null=True)),
                ("otp_expiredate", models.DateTimeField(blank=True, null=True)),
                (
                    "otp_attemp",
                    models.IntegerField(
                        default=0, verbose_name="Telefon doğrulama deneme sayısı"
                    ),
                ),
                (
                    "about",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Hakkımda"
                    ),
                ),
                (
                    "education",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Eğitim"
                    ),
                ),
                (
                    "experience",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="Deneyim"
                    ),
                ),
                (
                    "tcno",
                    models.CharField(
                        blank=True,
                        max_length=11,
                        null=True,
                        verbose_name="TC Kimlik No",
                    ),
                ),
                (
                    "passport",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Pasaport No"
                    ),
                ),
                (
                    "isAdmin",
                    models.BooleanField(default=False, verbose_name="Firma Admin"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="saas.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.departments",
                        verbose_name="Departman",
                    ),
                ),
                (
                    "sube",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="user.sube",
                        verbose_name="Şube",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
