# Generated by Django 4.2.17 on 2025-03-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("saas", "0002_remove_company_orderformtemplate"),
        ("user", "0002_alter_employee_company_alter_employee_sube"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departments",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="saas.company",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="user.departments",
                verbose_name="Departman",
            ),
        ),
    ]
